# A sample file for logger/listener/listen.py
##
# To run, type:
#
#    logger/listener/listen.py --config_file test/configs/parallel_logger.yaml
#
# Dictionary key/value pairs are used as keyword arguments for creating a
# Listener. The keys "reader", "transform" and "writer" are special-cased to
# indicate that the respective entities should be instantiated (recursively,
# if necessary).

# We have two readers, enclosed in a list. They will be run in
# parallel. The "interval" kwarg tells the TextFileReader to read one
# line from its file every interval seconds.
readers:
- class: TextFileReader
  kwargs:    # initialization kwargs
    file_spec: LICENSE
    interval: 1
- class: TextFileReader
  kwargs:    # initialization kwargs
    file_spec: README.md
    interval: 0.5

# No transforms

# Only a single writer, not enclosed in a list, to demonstrate/test
# that lists are only needed if we've got multiple components.
writers:
  class: TextFileWriter
   # no initialization kwargs; no filename, so write to stdout

