loggers:
  gps:
    configs:
    - gps->off
    - gps->file/cached
  psxn:
    configs:
    - psxn->off
    - psxn->file/cached
  winch:
    configs:
    - winch->off
    - winch->file/cached
  output_pos:
    configs:
    - output_pos->off
    - output_pos->file
  output_pos_normalized:
    configs:
    - output_pos_normalized->off
    - output_pos_normalized->file
  output_psxn:
    configs:
    - output_psxn->off
    - output_psxn->file
  output_winch:
    configs:
    - output_winch->off
    - output_winch->file
  output_all:
    configs:
    - output_all->off
    - output_all->file

modes:
  'off':
    gps: gps->off
    psxn: psxn->off
    winch: winch->off
    output_pos: output_pos->off
    output_pos_normalized: output_pos_normalized->off
    output_psxn: output_psxn->off
    output_winch: output_winch->off
    output_all: output_all->off
  underway:
    gps: gps->file/cached
    psxn: psxn->file/cached
    winch: winch->file/cached
    output_pos: output_pos->file
    output_pos_normalized: output_pos_normalized->file
    output_psxn: output_psxn->file
    output_winch: output_winch->file
    output_all: output_all->file

default_mode: "underway"

configs:
  gps->off: {}
  psxn->off: {}
  winch->off: {}
  output_pos->off: {}
  output_pos_normalized->off: {}
  output_psxn->off: {}
  output_winch->off: {}
  output_all->off: {}

  ###################################################################
  ## GPS
  ###################################################################
  gps->file/cached:
    name: gps->file/cached
    # First, read UDP or serial data
    readers:
    - class: UDPReader
      kwargs:
        port: 55000
    # Next, add timestamp and prefix since all outputs share these
    transforms:
    - class: TimestampTransform
    - class: PrefixTransform
      kwargs:
        prefix: "GPS"
    writers:
    # Next, add a parse transform only for the cached data writer
    - class: ComposedWriter
      kwargs:
        transforms:
        - class: ParseTransform
          kwargs:
            definition_path: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/devices/gps.yaml,/opt/openrvdas/local/devices/Trimble.yaml
        writers:
        - class: CachedDataWriter
          kwargs:
            data_server: localhost:8766
    # Finally, write the timestamped and prefixed raw data to log
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/gps.log
        truncate: True

  ###################################################################
  ## PSXN
  ###################################################################
  psxn->file/cached:
    name: psxn->file/cached
    readers:
    - class: UDPReader
      kwargs:
        port: 55108
    transforms:
    - class: TimestampTransform
    - class: PrefixTransform
      kwargs:
        prefix: "PSXN"
    writers:
    - class: ComposedWriter
      kwargs:
        transforms:
        - class: ParseTransform
          kwargs:
            definition_path: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/devices/psxn.yaml
        writers:
        - class: CachedDataWriter
          kwargs:
            data_server: localhost:8766
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/psxn.log
        truncate: True

  ###################################################################
  ## Winch
  ###################################################################
  winch->file/cached:
    name: winch->file/cached
    readers:
    - class: UDPReader
      kwargs:
        port: 55801
    transforms:
    - class: TimestampTransform
    - class: PrefixTransform
      kwargs:
        prefix: "WINCH"
    # Extra spaces in winch data will mess up ParseTransform
    - class: RegexReplaceTransform
      kwargs:
        patterns: {'\s+,': ',', ',\s+': ','}
    writers:
    - class: ComposedWriter
      kwargs:
        transforms:
        - class: ParseTransform
          kwargs:
            definition_path: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/devices/winch.yaml
        writers:
        - class: CachedDataWriter
          kwargs:
            data_server: localhost:8766
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/winch.log
        truncate: True

  ###################################################################
  ## Position output
  ###################################################################
  output_pos->file:
    name: output_pos->file
    readers:
    - class: CachedDataReader
      kwargs:
        data_server: localhost:8766
        subscription:
          fields:
            GPSLatitude:
              seconds: 0
            GPSNorS:
              seconds: 0
            GPSLongitude:
              seconds: 0
            GPSEorW:
              seconds: 0
    transforms:
    - class: FormatTransform
      kwargs:
        format_str: "{GPSLatitude}, {GPSEorW}, {GPSLongitude}, {GPSNorS}"
    - class: TimestampTransform
      kwargs:
        time_format: "%Y/%m/%d, %H:%M:%S.%f"
        sep: ", "
    writers:
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/output_pos.csv
        header: "DATE_GMT, TIME_GMT, LATITUDE, E_OR_W, LONGITUDE, N_OR_S"
        truncate: True

  ###################################################################
  ## Normalized position output
  ###################################################################
  output_pos_normalized->file:
    readers:
    - class: CachedDataReader
      kwargs:
        data_server: localhost:8766
        subscription:
          fields:
            GPSLatitude:
              seconds: 0
            GPSNorS:
              seconds: 0
            GPSLongitude:
              seconds: 0
            GPSEorW:
              seconds: 0
    # Example of custom transform
    transforms:
    - class: NormalizeLatLonTransform
      module: contrib.whoi.logger.transforms.normalize_lat_lon_transform
    - class: FormatTransform
      kwargs:
        format_str: "{SignedLatitude}, {SignedLongitude}"
    - class: TimestampTransform
      kwargs:
        time_format: "%Y/%m/%d, %H:%M:%S.%f"
        sep: ", "
    writers:
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/output_pos_normalized.csv
        header: "DATE_GMT, TIME_GMT, LATITUDE, LONGITUDE"
        truncate: True

  ###################################################################
  ## PSXN output
  ###################################################################
  output_psxn->file:
    name: output_psxn->file
    readers:
    - class: CachedDataReader
      kwargs:
        data_server: localhost:8766
        subscription:
          fields:
            PSXNMessageType:
              seconds: 0
            PSXNRoll:
              seconds: 0
            PSXNPitch:
              seconds: 0
            PSXNHeadingTrue:
              seconds: 0
            PSXNHeave:
              seconds: 0
    transforms:
    - class: FormatTransform
      kwargs:
        format_str: "{PSXNMessageType}, {PSXNRoll}, {PSXNPitch}, {PSXNHeadingTrue}, {PSXNHeave}"
    - class: TimestampTransform
      kwargs:
        time_format: "%Y/%m/%d, %H:%M:%S.%f"
        sep: ", "
    writers:
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/output_psxn.csv
        header: "DATE_GMT, TIME_GMT, MESSAGE_TYPE, ROLL, PITCH, HEADING_TRUE, HEAVE"
        truncate: True

  ###################################################################
  ## Winch output
  ###################################################################
  output_winch->file:
    name: output_winch->file
    readers:
    - class: CachedDataReader
      kwargs:
        data_server: localhost:8766
        subscription:
          fields:
            WinchName:
              seconds: 0
            WinchNoIdea:
              seconds: 0
            WinchTension:
              seconds: 0
            WinchPayoutSpeed:
              seconds: 0
            WinchPayout:
              seconds: 0
    transforms:
    - class: FormatTransform
      kwargs:
        format_str: "{WinchName}, {WinchNoIdea}, {WinchTension}, {WinchPayoutSpeed}, {WinchPayout}"
    - class: TimestampTransform
      kwargs:
        time_format: "%Y/%m/%d, %H:%M:%S.%f"
        sep: ", "
    writers:
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/output_winch.csv
        header: "DATE_GMT, TIME_GMT, NAME, NO_IDEA, TENSION, PAYOUT_SPEED, PAYOUT"
        truncate: True

  ###################################################################
  ## All output fields
  ###################################################################
  output_all->file:
    name: output_all->file
    readers:
    - class: CachedDataReader
      kwargs:
        data_server: localhost:8766
        subscription:
          fields:
            # All of the output fields
            # GPS fields
            GPSLatitude:
              seconds: 0
            GPSNorS:
              seconds: 0
            GPSLongitude:
              seconds: 0
            GPSEorW:
              seconds: 0
            # PSXN fields
            PSXNMessageType:
              seconds: 0
            PSXNRoll:
              seconds: 0
            PSXNPitch:
              seconds: 0
            PSXNHeadingTrue:
              seconds: 0
            PSXNHeave:
              seconds: 0
            # Winch fields
            WinchName:
              seconds: 0
            WinchNoIdea:
              seconds: 0
            WinchTension:
              seconds: 0
            WinchPayoutSpeed:
              seconds: 0
            WinchPayout:
              seconds: 0
    writers:
    - class: TextFileWriter
      kwargs:
        filename: /home/befo/Desktop/WHOI/underway/underway_rvdas/underway_rvdas_csv/atlantis/output/atlantis.log
        truncate: True